"""
Módulo de Datos Estáticos
-------------------------
Contiene las estructuras de datos (diccionarios y listas) que almacenan 
las efemérides diarias, así como las traducciones de meses y días al español.
"""
dias_espaniol = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]
meses_espaniol = {
    "01": "Enero",
    "02": "Febrero",
    "03": "Marzo",
    "04": "Abril",
    "05": "Mayo",
    "06": "Junio",
    "07": "Julio",
    "08": "Agosto",
    "09": "Septiembre",
    "10": "Octubre",
    "11": "Noviembre",
    "12": "Diciembre"
}
efemerides = {
    # ================= ENERO =================
    "01-01": "¡Feliz Año Nuevo! 🎆",
    "01-02": "Día del Introvertido. ¡Ideal para codear sin distracciones! 💻",
    "01-03": "Día de organizar el entorno virtual en Python 🐍",
    "01-04": "Día Mundial del Braille. ¡Asegura la accesibilidad en tus apps de React! 🌐",
    "01-05": "Día de estructurar las bases de datos en Oracle 🗄️",
    "01-06": "Bajada de Reyes en Perú 👑",
    "01-07": "Día de probar nuevos mods en ARK: Survival Evolved 🦖",
    "01-08": "¡Día de pulir tu perfil de GitHub para buscar prácticas! 💼",
    "01-09": "Día de repasar conceptos de Programación Orientada a Objetos 🧩",
    "01-10": "Día de buscar monitores en Mercado Libre 🛒",
    "01-11": "Día de aprender un nuevo hook en React ⚛️",
    "01-12": "Día de hacer deploy de tu backend en FastAPI 🚀",
    "01-13": "Día Mundial del Sticker. ¡A llenar el laptop de pegatinas! 💻",
    "01-14": "Día de armar un buen documento en LaTeX 📄",
    "01-15": "Día del Compositor. ¡Pero tú compones líneas de código! 🎵",
    "01-16": "Día de dominar servidores y peticiones asíncronas en Python ⚡",
    "01-17": "Día de jugar con la terminal de Linux 🐧",
    "01-18": "Aniversario de Lima 🏛️",
    "01-19": "Día de revisar el hardware: ¿necesitas más RAM? 🧠",
    "01-20": "Día de domar un Giganotosaurus en ARK 🦕",
    "01-21": "Día de la Abrazadera. ¡Abraza a tu router! 📶",
    "01-22": "Día de resolver bugs de concurrencia 🐛",
    "01-23": "Día de leer sobre metodologías ágiles y PMBOK 📚",
    "01-24": "Día Mundial de la Educación 🎓",
    "01-25": "Día de optimizar consultas SQL 📊",
    "01-26": "Día de la Educación Ambiental. ¡Apaga la PC si no la usas! 🌱",
    "01-27": "Día de refactorizar tu proyecto Full-Stack 🛠️",
    "01-28": "Día de la Acción frente al Calentamiento Global (y el sobrecalentamiento de tu CPU) 🌡️",
    "01-29": "Día del Rompecabezas. ¡Como entender código ajeno! 🧩",
    "01-30": "Día Escolar de la No Violencia y la Paz 🕊️",
    "01-31": "Fin de mes: ¡Día de hacer backup a toda tu base de datos! 💾",

    # ================= FEBRERO =================
    "02-01": "Día de planificar los sprints del mes 🏃",
    "02-02": "Día del Pisco Sour. ¡Salud por el código que compila a la primera! 🍹",
    "02-03": "Día de aprender a configurar Docker 🐳",
    "02-04": "Día Mundial contra el Cáncer 🎗️",
    "02-05": "Día del Clima. ¡Cuidado con la humedad en tu placa madre! ☔",
    "02-06": "Día de buscar ofertas en AliExpress 📦",
    "02-07": "Día de enviar currículums a Credicorp o GMI 🏦",
    "02-08": "Día del Internet Seguro 🔒",
    "02-09": "Día de repasar algoritmos de ordenamiento 🧮",
    "02-10": "Día de conectar React con FastAPI exitosamente 🔌",
    "02-11": "Día de la Mujer y la Niña en la Ciencia 👩‍🔬",
    "02-12": "Día de probar comandos nuevos en ARK 🎮",
    "02-13": "Día Mundial de la Radio 📻",
    "02-14": "Día de San Valentín ❤️ (o de amar tu código)",
    "02-15": "Día de compilar el proyecto sin errores 🎉",
    "02-16": "Día de revisar la documentación de una API REST 📖",
    "02-17": "Día de diseñar diagramas Entidad-Relación 📐",
    "02-18": "Día Internacional del Síndrome de Asperger 🧠",
    "02-19": "Día de probar nuevas librerías de componentes en React UI 🎨",
    "02-20": "Día del Emoliente, Quinua y Maca (¡combustible para programar!) ☕",
    "02-21": "¡Día de pruebas de código! 💻",
    "02-22": "Día de relajarse explorando cuevas en ARK ⛏️",
    "02-23": "Día del Compromiso Internacional del Control del Mercurio 🧪",
    "02-24": "Día de limpiar la caché del navegador 🧹",
    "02-25": "Día de aprender atajos de teclado en VS Code ⌨️",
    "02-26": "Día de configurar tus variables de entorno en `.env` 🔐",
    "02-27": "Día de Pokémon. ¡Atrapa todos los bugs! ⚡",
    "02-28": "Día de preparar tu entorno de desarrollo para marzo 🗓️",
    "02-29": "¡Día Bisiesto! Un día extra de vida... para seguir codeando 🐸",

    # ================= MARZO =================
    "03-01": "Día de la Cero Discriminación 🤝",
    "03-02": "Día de aprender a lidiar con CORS en FastAPI 🚧",
    "03-03": "Día Mundial de la Naturaleza 🌳",
    "03-04": "Día de organizar tus repositorios en GitHub 📂",
    "03-05": "Día de la Eficiencia Energética 💡",
    "03-06": "Día de limpiar tu escritorio y cables 🔌",
    "03-07": "Día de practicar tu lógica con C básico ⚙️",
    "03-08": "Día Internacional de la Mujer 👩",
    "03-09": "Día de leer un buen libro de Ingeniería de Software 📘",
    "03-10": "Día del Riñón. ¡No tomes tanta bebida energizante! 💧",
    "03-11": "Día de crear interfaces de usuario responsivas 📱",
    "03-12": "Día de probar la velocidad de tu red 🌐",
    "03-13": "Día de explorar nuevas extensiones en VS Code 🛠️",
    "03-14": "Día de Pi (3.14). ¡Perfecto para cálculos en Python! 🥧",
    "03-15": "Día Mundial de los Derechos del Consumidor 🛒",
    "03-16": "Inicio del año escolar/académico (¡a estudiar!) 🎒",
    "03-17": "Día de San Patricio 🍀 (¡Suerte compilando!)",
    "03-18": "Día de optimizar el renderizado en React 🏎️",
    "03-19": "Día del Artesano. ¡El código también es arte! 🎨",
    "03-20": "Día Internacional de la Felicidad 😊",
    "03-21": "Día Internacional del Síndrome de Down 🧬",
    "03-22": "Día Mundial del Agua 💧",
    "03-23": "Día Meteorológico Mundial 🌤️",
    "03-24": "Día de la Lucha contra la Tuberculosis 🫁",
    "03-25": "Día del Niño por Nacer 👶",
    "03-26": "La Hora del Planeta 🌍",
    "03-27": "Día Internacional del Teatro 🎭",
    "03-28": "Día de dominar JWT y autenticación en FastAPI 🔑",
    "03-29": "Día de estructurar un nuevo proyecto en la universidad 🏫",
    "03-30": "Día de crear mutaciones complejas en bases de datos 🧬",
    "03-31": "Día Mundial del Backup (¡Copia de seguridad ya!) 💾",

    # ================= ABRIL =================
    "04-01": "Día de las Bromas (April Fools'). ¡Cuidado con el código espagueti! 🤡",
    "04-02": "Día Mundial de Concienciación sobre el Autismo 💙",
    "04-03": "Día de resolver un problema difícil en Stack Overflow 🤓",
    "04-04": "Día del Error 404 (Not Found). ¿Dónde quedó ese archivo? 🕵️‍♂️",
    "04-05": "Día de practicar con flexbox y CSS Grid 📐",
    "04-06": "Día Mundial de la Actividad Física (¡Levántate de la silla!) 🏃‍♂️",
    "04-07": "Día Mundial de la Salud 🩺",
    "04-08": "Día de redactar tu informe universitario en LaTeX 📜",
    "04-09": "Día del Heroísmo Infantil Peruano (Alejandro Sánchez Arteaga) 🇵🇪",
    "04-10": "Día de la Ciencia y la Tecnología 🔬",
    "04-11": "Día del Arqueólogo. ¡Explorando código legado! 🏺",
    "04-12": "Nacimiento del Inca Garcilaso de la Vega 🖋️",
    "04-13": "Día de buscar un buen cargador barato en internet 🔌",
    "04-14": "Día de las Américas 🌎",
    "04-15": "Día del Poeta Peruano 📜",
    "04-16": "Día del Emprendimiento. ¡Idea tu propia startup! 💡",
    "04-17": "Día de la Cruz Roja Peruana ⛑️",
    "04-18": "Día de la Educación Básica Alternativa 📚",
    "04-19": "Día del Primer Congreso de la República del Perú 🏛️",
    "04-20": "Día del Hardware Libre. ¡Revisa esos componentes! 🪛",
    "04-21": "Día Mundial de la Creatividad y la Innovación 🧠",
    "04-22": "Día de la Tierra 🌍",
    "04-23": "Día del Idioma Castellano y del Libro 📖",
    "04-24": "Día de diseñar un buen esquema relacional en MySQL 🐬",
    "04-25": "Día Internacional de las Niñas en las TIC 👩‍💻",
    "04-26": "Día Mundial de la Propiedad Intelectual ⚖️",
    "04-27": "Día Internacional del Diseño Web 🎨",
    "04-28": "Día Mundial de la Seguridad y Salud en el Trabajo 👷‍♂️",
    "04-29": "Día del Vendedor. ¡Vende tu proyecto en la expo de la U! 🗣️",
    "04-30": "Día de domar Pteranodones en ARK para viajar rápido 🦅",

    # ================= MAYO =================
    "05-01": "Día del Trabajo 👷",
    "05-02": "Aniversario del Combate del Dos de Mayo ⚔️",
    "05-03": "Día de la Libertad de Prensa 📰",
    "05-04": "Día de Star Wars (May the 4th be with you). ¡Usa la fuerza al programar! 🌌",
    "05-05": "Día Mundial de la Contraseña (¡Cambia ese '123456'!) 🔐",
    "05-06": "Día de estudiar patrones de diseño de software 🏗️",
    "05-07": "Día de repasar Pydantic en FastAPI 🛡️",
    "05-08": "Día Mundial de la Cruz Roja 🏥",
    "05-09": "Día de Europa 🇪🇺",
    "05-10": "Día de revisar los logs del servidor 📋",
    "05-11": "Aniversario de la acción heroica de María Parado de Bellido 🇵🇪",
    "05-12": "Día Escolar de las Matemáticas ➕",
    "05-13": "Día de escribir tests unitarios (que siempre postergas) 🧪",
    "05-14": "Día de implementar WebSockets para tiempo real ⏱️",
    "05-15": "Día Internacional de la Familia 👨‍👩‍👦",
    "05-16": "Día de la Luz. ¡Cambia a Dark Mode! 🌙",
    "05-17": "Día Mundial de Internet y las Telecomunicaciones 🌐",
    "05-18": "Sacrificio de Túpac Amaru II y Micaela Bastidas 🇵🇪",
    "05-19": "Día de refinar las promesas y async/await en JS ⏳",
    "05-20": "Día de la Metrología. ¡Mide el rendimiento de tu app! 📏",
    "05-21": "El Combate de Iquique 🚢",
    "05-22": "Día Internacional de la Diversidad Biológica 🌿",
    "05-23": "Día de organizar la lógica de negocio en tu backend ⚙️",
    "05-24": "Día de aprender a manejar estados globales en React 🌐",
    "05-25": "Día del Orgullo Friki / Día de la Educación Inicial 🤓",
    "05-26": "Día de la Integración Andina ⛰️",
    "05-27": "Día del Idioma Nativo en Perú 🗣️",
    "05-28": "Día Internacional del Juego (¡Saca unas horas para ARK!) 🎮",
    "05-29": "Día del Empleado Público 🏢",
    "05-30": "Día Nacional de la Papa 🥔",
    "05-31": "Día Mundial Sin Tabaco / Solidaridad Nacional 🚭",

    # ================= JUNIO =================
    "06-01": "Día de la Cruz Roja Peruana (Fundación) ⛑️",
    "06-02": "Día del Prócer José Faustino Sánchez Carrión 🇵🇪",
    "06-03": "Día de revisar el thermal paste de tu CPU ❄️",
    "06-04": "Día de la Cultura Afroperuana 🥁",
    "06-05": "Día Mundial del Medio Ambiente 🌍",
    "06-06": "Día de limpiar módulos de Node.js (¡Pesa mucho!) 🗑️",
    "06-07": "Día de la Bandera del Perú / Batalla de Arica 🇵🇪",
    "06-08": "Día del Ingeniero Peruano. ¡A celebrar tu futura profesión! 👷‍♂️",
    "06-09": "Día de estudiar arquitecturas de microservicios 🏢",
    "06-10": "Día de probar tu API en Postman 📬",
    "06-11": "Día de diseñar una landing page atractiva 🎨",
    "06-12": "Día Mundial contra el Trabajo Infantil 👧🧒",
    "06-13": "Día de compilar el kernel (o simplemente reiniciar la PC) 🐧",
    "06-14": "Día Mundial del Donante de Sangre 🩸",
    "06-15": "Día de la Canción Andina 🎵",
    "06-16": "Día de investigar cómo escalar bases de datos Oracle 📈",
    "06-17": "Día de Lucha contra la Desertificación 🌵",
    "06-18": "Día de hacer un merge request sin conflictos 🔀",
    "06-19": "Día de aprender a usar Git Rebase 🌳",
    "06-20": "Día del WiFi. ¡Que no se caiga en plena ranked! 📶",
    "06-21": "Día del Solsticio de Invierno ❄️",
    "06-22": "Día de programar scripts de automatización en Python 🤖",
    "06-23": "Día de la Mujer en la Ingeniería 👩‍💻",
    "06-24": "Día del Campesino y Fiesta del Inti Raymi ☀️",
    "06-25": "Día de buscar un buen mod de construcción en ARK 🏰",
    "06-26": "Día Internacional contra el Tráfico Ilícito de Drogas 🚫",
    "06-27": "Día de las Micro y Pequeñas Empresas 🏪",
    "06-28": "Día Nacional del Ceviche 🐟🍋",
    "06-29": "Día del Papa / San Pedro y San Pablo ⛪",
    "06-30": "Día de las Redes Sociales 📱",

    # ================= JULIO =================
    "07-01": "Día del Parque Nacional Huascarán 🏔️",
    "07-02": "Día de pulir tu lógica matemática para la universidad 🔢",
    "07-03": "Día Internacional Libre de Bolsas de Plástico 🛍️",
    "07-04": "Día de repasar conceptos de ciberseguridad 🛡️",
    "07-05": "Día de hacer animaciones en CSS 🎞️",
    "07-06": "Día del Maestro en Perú 👨‍🏫",
    "07-07": "Descubrimiento de Machu Picchu / Santuario Histórico 🏛️",
    "07-08": "Día de optimizar el SEO de tus aplicaciones web 🔍",
    "07-09": "Día de las Batallas de Pucará, Marcavalle y Concepción ⚔️",
    "07-10": "Día de investigar sobre Machine Learning en Python 🤖",
    "07-11": "Día Mundial de la Población 👨‍👩‍👧‍👦",
    "07-12": "Día del Guía de Turismo 🎒",
    "07-13": "Día de programar la navegación en React Router 🗺️",
    "07-14": "Día de instalar dependencias sin que nada explote 💣",
    "07-15": "Aniversario de la muerte del Coronel Leoncio Prado 🇵🇪",
    "07-16": "Día de hacer mantenimiento físico a tu laptop 💻",
    "07-17": "Día Mundial del Emoji 🥳",
    "07-18": "Día de revisar el plan de estudios de tu carrera 📋",
    "07-19": "Día de aprender a configurar Nginx 🚦",
    "07-20": "Día del Amigo (¡Saluda a tus compas de la universidad!) 🤜🤛",
    "07-21": "Día de domar un T-Rex de nivel alto en ARK 🦖",
    "07-22": "Día de crear vistas SQL complejas 👁️",
    "07-23": "Día del héroe capitán FAP José Abelardo Quiñones 🛩️",
    "07-24": "Día de los hechos de armas de Zarumilla / Nacimiento de Simón Bolívar ⚔️",
    "07-25": "Día de subir tu portafolio a Vercel o Netlify ☁️",
    "07-26": "Día de jugar con Raspberry Pi o Arduino 🍓",
    "07-27": "Día de prepararse para Fiestas Patrias 🔴⚪🔴",
    "07-28": "¡Día de la Proclamación de la Independencia del Perú! 🇵🇪🎉",
    "07-29": "Gran Parada Militar y Desfile Cívico 🪖",
    "07-30": "Día de descansar después de tanta celebración patria 🛌",
    "07-31": "Día de preparar los proyectos para el nuevo mes 🗓️",

    # ================= AGOSTO =================
    "08-01": "Día Nacional de la Alpaca 🦙",
    "08-02": "Día del Cajón Peruano 📦",
    "08-03": "Día de optimizar los tiempos de carga en React ⚡",
    "08-04": "Día de revisar el uso de memoria de tus variables 🧠",
    "08-05": "Día de estudiar para los exámenes parciales 📝",
    "08-06": "Batalla de Junín ⚔️",
    "08-07": "Día de limpiar el teclado (¡tiene migas de pan!) ⌨️",
    "08-08": "Día de los gráficos web con Canvas o Chart.js 📈",
    "08-09": "Día Internacional de las Poblaciones Indígenas 🌎",
    "08-10": "Día de investigar nuevas tecnologías en la nube (AWS/GCP) ☁️",
    "08-11": "Día de depurar el backend línea por línea 🐛",
    "08-12": "Día Internacional de la Juventud 👦",
    "08-13": "Día Internacional del Zurdo ✍️",
    "08-14": "Día de aprender a escribir macros en Excel 📊",
    "08-15": "Aniversario de Arequipa 🌋",
    "08-16": "Día de configurar endpoints seguros en FastAPI 🔐",
    "08-17": "Muerte del General don José de San Martín 🕊️",
    "08-18": "Día de diseñar mockups en Figma 🎨",
    "08-19": "Día de la Fotografía 📸",
    "08-20": "Día del Callao. ¡A comer un rico pan con chicharrón! 🥪",
    "08-21": "Día de la poesía y el buen código 📜",
    "08-22": "Día Mundial del Folclor 💃",
    "08-23": "Día del Internauta y del Hashtag #️⃣",
    "08-24": "Día de dominar SQLAlchemy 🗃️",
    "08-25": "Día de Linux. ¡Larga vida al código abierto! 🐧",
    "08-26": "Día del Adulto Mayor en Perú 👵👴",
    "08-27": "Día de la Defensa Nacional 🛡️",
    "08-28": "Reincorporación de Tacna al seno de la Patria 🇵🇪",
    "08-29": "Día del Gamer. ¡Una maratón de ARK merecida! 🎮",
    "08-30": "Día de Santa Rosa de Lima 🌹",
    "08-31": "Día del Mariscal Ramón Castilla 📜",

    # ================= SEPTIEMBRE =================
    "09-01": "Día del Árbol 🌲",
    "09-02": "Día de aprender a manejar excepciones en Python ⚠️",
    "09-03": "Día de optimizar imágenes para la web 🖼️",
    "09-04": "Día del nacimiento de Google (1998) 🔍",
    "09-05": "Día de las Mujeres Indígenas 👩🏽",
    "09-06": "Día de estudiar concurrencia e hilos de procesamiento 🧵",
    "09-07": "Día de los Derechos Cívicos de la Mujer 🗳️",
    "09-08": "Día Internacional de la Alfabetización y del Periodista Peruano 📰",
    "09-09": "Día del Sudoku y Día del Tester de Software 🐛",
    "09-10": "Día Mundial de Prevención del Suicidio 🫂",
    "09-11": "Día de aprender sobre inyección SQL y cómo evitarla 🛡️",
    "09-12": "Día del Programador en año bisiesto (#256Day) 👨‍💻",
    "09-13": "Día del Programador (en año normal, ¡pero celéralo también!) 💻",
    "09-14": "Día de la Familia Peruana 👨‍👩‍👧",
    "09-15": "Día Internacional de la Democracia 🗳️",
    "09-16": "Día de la Capa de Ozono 🌍",
    "09-17": "Día de revisar el estado de tu disco SSD 💽",
    "09-18": "Día de hacer diagramas de flujo claros 📝",
    "09-19": "Día de probar tu interfaz en dispositivos móviles 📱",
    "09-20": "Día del Software Libre 🕊️",
    "09-21": "Día Internacional de la Paz ☮️",
    "09-22": "Día Mundial Sin Auto (¡Viaja en internet!) 🚲",
    "09-23": "Día de la Primavera y la Juventud / Día de la Aviación Nacional 🌸",
    "09-24": "Día de las Fuerzas Armadas del Perú 🪖",
    "09-25": "Día de explorar frameworks de CSS como Tailwind 🎨",
    "09-26": "Día Internacional para la Eliminación de las Armas Nucleares ☢️",
    "09-27": "Día Mundial del Turismo ✈️",
    "09-28": "Día Internacional del Derecho de Acceso Universal a la Información 🌐",
    "09-29": "Día de estructurar bien las props en React ⚛️",
    "09-30": "Día Internacional del Podcast (¡Escucha uno de tech!) 🎧",

    # ================= OCTUBRE =================
    "10-01": "Día del Periodismo Peruano 🗞️",
    "10-02": "Día Internacional de la No Violencia 🕊️",
    "10-03": "Día del Odontólogo. ¡No olvides lavarte los dientes tras el trasnocho! 🦷",
    "10-04": "Día de San Francisco de Asís y Día de los Animales 🐶",
    "10-05": "Día de la Medicina Peruana (Daniel Alcides Carrión) 🩺",
    "10-06": "Día del Ilustre Tradicionalista Don Ricardo Palma 📚",
    "10-07": "Día de aprender a implementar pagos en línea 💳",
    "10-08": "Combate de Angamos / Día de la Educación Física ⚓",
    "10-09": "Día de los Eventos Curiosos (¡como un bug que se arregla solo!) 🪄",
    "10-10": "Día de la Acción Cívica 🇵🇪",
    "10-11": "Día de dominar las funciones flecha en JavaScript 🏹",
    "10-12": "Descubrimiento de América / Día de los Pueblos Originarios 🌎",
    "10-13": "Día de la Reducción de Desastres (¡Haz backup de nuevo!) 🚨",
    "10-14": "Día de leer blogs de Ingeniería de Software 📖",
    "10-15": "Día de usar `git blame` para ver quién rompió el código 👀",
    "10-16": "Día Nacional de la Persona con Discapacidad / Día de la Alimentación 🍎",
    "10-17": "Día de estructurar un buen README.md 📄",
    "10-18": "Procesión del Señor de los Milagros. ¡El mes morado! 💜",
    "10-19": "Día de diseñar bases de datos escalables 📊",
    "10-20": "Día Internacional de la Estadística 📈",
    "10-21": "Día Nacional del Ahorro de Energía 💡",
    "10-22": "Día de explorar el desarrollo de mods para juegos 🎮",
    "10-23": "Día de la Aviación Comercial. ¡A volar con FastAPI! ✈️",
    "10-24": "Día de las Naciones Unidas 🇺🇳",
    "10-25": "Día de refactorizar componentes antiguos ♻️",
    "10-26": "Día de investigar sobre arquitectura de software empresarial 🏢",
    "10-27": "Día de armar tu base en ARK contra incursiones 🏰",
    "10-28": "Día de buscar pasantías tecnológicas 💼",
    "10-29": "Día de revisar la accesibilidad (a11y) de tu web ♿",
    "10-30": "Día de hacer pruebas de estrés al servidor 💥",
    "10-31": "Día de la Canción Criolla 🎸 y de Halloween 🎃 (¡Errores de miedo!)",

    # ================= NOVIEMBRE =================
    "11-01": "Día de Todos los Santos y Semana Nacional Forestal 🕊️",
    "11-02": "Día de los Fieles Difuntos 🕯️",
    "11-03": "Día de limpiar el polvo de los ventiladores del PC 🌬️",
    "11-04": "Rebelión de Túpac Amaru II 🇵🇪",
    "11-05": "Día de revisar el rendimiento y Big O notation de tu app ⏱️",
    "11-06": "Día de actualizar tus librerías de Python 🐍",
    "11-07": "Día de crear gráficos dinámicos en el frontend 📉",
    "11-08": "Día de configurar pipelines CI/CD 🚀",
    "11-09": "Día del Inventor. ¡Tú creas soluciones digitales! 💡",
    "11-10": "Día de la Biblioteca Escolar. ¡Ve a la de la universidad! 📚",
    "11-11": "Día de los Solteros (Ofertas en AliExpress, ¡aprovecha para compras!) 🛍️",
    "11-12": "Aniversario de la propuesta de la World Wide Web (1990) 🌐",
    "11-13": "Día de aprender a protegerte del Cross-Site Scripting (XSS) 🛡️",
    "11-14": "Día del Bibliotecario 📖",
    "11-15": "Día de usar `console.log()` para depurar toda la noche 🕵️‍♂️",
    "11-16": "Día de la Tolerancia. ¡Sé tolerante con el código legado! 🧘",
    "11-17": "Día de aprender sobre Normalización de Bases de Datos 🗄️",
    "11-18": "Día de crear formularios robustos en React 📝",
    "11-19": "Día Internacional del Hombre 👨",
    "11-20": "Día de la Declaración Universal de los Derechos del Niño 👧🧒",
    "11-21": "Día Mundial de la Televisión 📺",
    "11-22": "Día de optimizar peticiones HTTP 🌐",
    "11-23": "Día de revisar qué framework está de moda hoy en JS 🌟",
    "11-24": "Día de planificar el proyecto final de la carrera 🎓",
    "11-25": "Día de la No Violencia contra la Mujer 🟣",
    "11-26": "Aniversario de la creación del USB (1994) 🔌",
    "11-27": "Batalla de Tarapacá / Andrés Avelino Cáceres 🇵🇪",
    "11-28": "Día Mundial del Ingeniero de Sistemas y Black Friday 🛒",
    "11-29": "Día Internacional del Ingeniero de Sistemas 👨‍💻",
    "11-30": "Día Internacional de la Seguridad Informática 🛡️",

    # ================= DICIEMBRE =================
    "12-01": "Día Mundial de la Lucha contra el SIDA 🔴",
    "12-02": "Día de diseñar un esquema de base de datos final 📐",
    "12-03": "Día Internacional de las Personas con Discapacidad ♿",
    "12-04": "Día de compilar el último proyecto del semestre 🎓",
    "12-05": "Día del Bombero Voluntario del Perú 🚒",
    "12-06": "Día de apagar la PC y descansar la vista 👁️",
    "12-07": "Día de revisar notas y cerrar cursos 💯",
    "12-08": "Día de la Inmaculada Concepción ⛪",
    "12-09": "Batalla de Ayacucho ⚔️",
    "12-10": "Día de la Declaración Universal de los Derechos Humanos 🤝",
    "12-11": "Día Internacional de las Montañas 🏔️",
    "12-12": "Día de ordenar tus finanzas y presupuesto para hardware nuevo 💵",
    "12-13": "Día de actualizar tu currículum de fin de año 📄",
    "12-14": "Día de la Cooperación. ¡Trabajo en equipo en la U! 👥",
    "12-15": "Día de buscar mods navideños para ARK 🎄🦕",
    "12-16": "Día de armar tu arbolito navideño (o un árbol binario) 🎄",
    "12-17": "Día de evaluar qué lenguajes aprenderás el próximo año 🤔",
    "12-18": "Fin de clases escolar y universitario en Perú 🎒🎉",
    "12-19": "Día de formatear la computadora para empezar fresco 💽",
    "12-20": "Día de organizar la cena navideña 🦃",
    "12-21": "Solsticio de Verano en el hemisferio sur ☀️",
    "12-22": "Día de comer panetón mientras resuelves un bug 🍞",
    "12-23": "Día de las compras de pánico de última hora 🎁",
    "12-24": "Nochebuena. ¡Tiempo en familia! 👪",
    "12-25": "¡Feliz Navidad! 🎄✨",
    "12-26": "Día de probar los gadgets tecnológicos que te regalaron 📱",
    "12-27": "Día de hacer retrospectiva tecnológica del año 🔙",
    "12-28": "Día de los Inocentes. (Push a producción en viernes) 🤡",
    "12-29": "Día de planear las metas de desarrollo personal 🎯",
    "12-30": "Día de hacer la última limpieza de repositorios del año 🧹",
    "12-31": "¡Fin de Año! Compilando el último código antes del brindis 🥂",
}
